# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages that have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: 'OWF Learn / ArcGIS Story Maps'
pages:
- Home: index.md
- Introduction: introduction.md
- Create an ArcGIS Online Account: create-account.md
- 'Create a Basic Map':
  - Overview: 'create-map/overview.md'
  - Choose a Basemap: 'create-map/choose-basemap.md'
  - Add Layers: 'create-map/add-layers.md'
  - Change the Style: 'create-map/change-style.md'
  - Configure Pop-ups: 'create-map/configure-popups.md'
  - Save the Map: 'create-map/save-map.md'
- Story Map Templates: story-map-templates.md
- 'Create a Story Map':
  - Overview: 'create-story-map/overview.md'
  - Tabbed Layout Example: 'create-story-map/tabbed-layout.md'
  - Side Accordion Layout Example: 'create-story-map/side-accordion-layout.md'
  - Bulleted Layout Example: 'create-story-map/bulleted-layout.md'
- Story Maps for Developers: developers.md
- 'Resources': resources.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
#theme: readthedocs
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-arcgis-story-maps
site_description:  'Open Water Foundation Learn ArcGIS Story Maps'
site_author:  'Open Water Foundation'
site_favicon:  'images/OWF-Logo-Favicon-32x32.png'
copyright:  'Copyright Open Water Foundation'
# Use extra CSS to customize styles, based o
extra_css:
  - 'css/extra-material-theme.css'
